Browser=Chrome

qaenv=https://freelance-learn-automation.vercel.app/login

stagenv=https://staging.learn-automation.com

prod=https://learn-automation.com

highlight=Yes

retry = 5

screenshotOnfailure=true

screenshotOnPassed=true

screenshotOnSkip=true